### ISSUE TITLE
"defaultPropertiesFileName" should be mentioned in examle usage or installation

### ISSUE THREAD

**Issue by KonradKarimi** [google/secrets-gradle-plugin#47]
Hello,

I've been struggling to use this plugin in my GitHub actions workflow. Locally everything worked fine. On GitHub action I've got known error:

`Attribute meta-data#com.google.android.geo.API_KEY@value at AndroidManifest.xml:32:13-44 requires a placeholder substitution but no value for <GOOGLE_MAPS_KEY> is provided.`

To mention in my workflow I've just passed local.properties content from GitHub action secret storage in my `workflow.yml` like that:
```
- name: Provide Local properties
  env:
    LOCAL_PROP: ${{ secrets.LOCAL_PROP }}
  run: echo $LOCAL_PROP > ./android/local.properties
```
When I explicitly added the default option in my `app/build.gradle`:
```
secrets {
    defaultPropertiesFileName = 'local.properties'
}
```
It finally started working! 😎 
To conclude I think it should be mentioned somewhere in the documentation that the `defaultPropertiesFileName` param might be required in some applications.
